### ISSUE TITLE
FYI XML to support exponentiation

### ISSUE THREAD

**Issue by hamishwillee** [olliw42/fastmavlink#11]
FYI We're modifying the MAVLink XSD validation file in https://github.com/ArduPilot/pymavlink/pull/920 to allow a bitmask value to be declared using the Python exponentiation operator. 

This makes it easier to immediately visualize which bit is set by a flag, because you can use the syntax 
```xml
<entry value="2**15" name="BIT15" />
```
rather than
```xml
<entry value="32768" name=" BIT15" />
```
This is transparent to mavgen because the parser evaluates the number before creating the generated headers. However it may affect other the rust parser
We're not updating the XML yet to allow other parsers time to update.

Any concerns, please raise on https://github.com/ArduPilot/pymavlink/pull/920

**Comment by olliw42** [comment]
MANY THX for informing me, this is really much appreciated.

I too would have preferred the more common '^' over '**', but I think it's anyway a very good addition, making things easier. Very cool.

**Comment by olliw42** [comment]
@hamishwillee 
I've looked into the code and also tested it: 
- like for mavgen 'value' is also passed through eval, and 2**x comes out correctly.
- for 'default' it seems neither mavgen nor fastmavlink really make use of the value.
It seems to me that fastmavlink is ready for exponentiation.
Thx again for bringing this up.

**Comment by hamishwillee** [comment]
Excellent

FWIW for 'default' it seems neither mavgen nor fastmavlink really make use of the value - yeah, its supposed to be a better form of documentation and might be used by a programming language that supports taking default values. No one has done that though.

**Comment by olliw42** [comment]
I'm looking forward for this new xsd to be merged :)

**Comment by hamishwillee** [comment]
Me too. No merge rights in that repo
