### ISSUE TITLE
Great Lib! License?

### ISSUE THREAD

**Issue by seeul8er** [olliw42/fastmavlink#12]
Hi!

I just wanted to stop by and say thank you for the great library! I want to use it with the v2.0 release of DroneBridge for ESP32. It is already working great. Sadly it is not common to find such a well-documented piece of software on GitHub. Thanks to the examples it was very straightforward to integrate and works very well on the ESP32.

I see you have not decided on the license, yet. Could you update that soon please, since in the current state I am not even sure I can use it for my projects. A missing license will also prevent others from adapting to your library.

**Comment by olliw42** [comment]
thx for the kind words and nice to see you found it useful.
fixed the license thing. Was long due anyway.
have fun 

(closing as settled)
