### ISSUE TITLE
Missing compatibility functions

### ISSUE THREAD

**Issue by noahbliss** [olliw42/fastmavlink#8]
I haven't gotten around to writing a proposed change for these yet, but ran into at least one function in the official lib which didn't seem to function (pun intended). 
```
mavlink_msg_command_long_encode
```

located in https://github.com/mavlink/c_library_v2/blob/master/common/mavlink_msg_command_long.h

**Comment by olliw42** [comment]
many thx

yes, the xxx_encode() functions are not provided, only the xxx_pack() functions

the xxx_encode() functions are however simply wrappers, https://github.com/mavlink/c_library_v2/blob/master/common/mavlink_msg_command_long.h#L193-L196. So it should be easy to add them.
Would you have a means to test if this working?

(I haven't used this mimicry for very very long and think have no test environment on my disk anymore, so would have to create one)

BTW, this mimicry won't emulate all and every function of the official lib, e.g. not the convenience functions you enable with MAVLINK_USE_CONVENIENCE_FUNCTIONS
BTW II: The flurry of mavlink_msg_xxx_get_yyy() functions are also not mimicri-ed (these also should be simple to add, but ...)

**Comment by olliw42** [comment]
see updated main branch.
closing
